#!/usr/bin/env bash
# Generate .env for lite deploy (SQLite, no Docker).
# Usage: ./deploy/init-env-lite.sh [domain]
#        FORCE=1 ./deploy/init-env-lite.sh  # overwrite existing .env
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DOMAIN="${1:-meti-pilates.com}"
OUT="$ROOT/.env"
DATA_DIR="/var/lib/meti-booking"

if [[ -f "$OUT" ]]; then
  if [[ "${FORCE:-}" != "1" ]]; then
    echo "ERROR: $OUT already exists."
    echo "  FORCE=1 ./deploy/init-env-lite.sh"
    exit 1
  fi
  cp "$OUT" "${OUT}.bak.$(date +%Y%m%d%H%M%S)"
fi

BETTER_AUTH_SECRET="$(openssl rand -base64 32)"
CRON_SECRET="$(openssl rand -hex 24)"
ENCRYPTION_KEY="$(openssl rand -base64 32)"
BASE_URL="https://${DOMAIN}"

cat > "$OUT" <<EOF
# Generated by deploy/init-env-lite.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Lite mode: no Docker, SQLite file database (low RAM).

DEPLOY_MODE=lite
DOMAIN=${DOMAIN}
METI_DATA_DIR=${DATA_DIR}
DATABASE_URL=file:${DATA_DIR}/data.db

BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
BETTER_AUTH_URL=${BASE_URL}
NEXT_PUBLIC_BETTER_AUTH_URL=${BASE_URL}

SELF_HOSTED=1
STUDIO_TIMEZONE=Asia/Nicosia
APP_URL=${BASE_URL}

CRON_SECRET=${CRON_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

PAYMENTS_ENABLED=0

RESEND_API_KEY=
EMAIL_FROM="MeTi Pilates <bookings@${DOMAIN}>"
STUDIO_NOTIFICATION_EMAIL=tyrri_meropi@hotmail.com

GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# ALLOW_DEMO_SEED=1
# DEMO_PASSWORD=YourSecurePassword123!
EOF

chmod 600 "$OUT"
mkdir -p "$DATA_DIR"

echo ""
echo "Wrote $OUT (DEPLOY_MODE=lite, SQLite)"
echo "  DOMAIN=${DOMAIN}"
echo "  DATABASE_URL=file:${DATA_DIR}/data.db"
echo ""
echo "Next:"
echo "  ./deploy/install-lite.sh   # once, if Node/Caddy not installed"
echo "  ./deploy/deploy-lite.sh"
