#!/usr/bin/env bash
# Generate secrets and write production .env for Hetzner deploy.
# Usage (from repo root):
#   ./deploy/init-env.sh
#   ./deploy/init-env.sh meti-pilates.com
#   FORCE=1 ./deploy/init-env.sh   # overwrite existing .env (backs up first)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

DOMAIN="${1:-meti-pilates.com}"
OUT="$ROOT/.env"

if [[ -f "$OUT" ]]; then
  if [[ "${FORCE:-}" != "1" ]]; then
    echo "ERROR: $OUT already exists."
    echo "  Backup and overwrite: FORCE=1 ./deploy/init-env.sh"
    echo "  Or edit manually:     nano .env"
    exit 1
  fi
  BACKUP="${OUT}.bak.$(date +%Y%m%d%H%M%S)"
  cp "$OUT" "$BACKUP"
  echo "Backed up existing .env → $BACKUP"
fi

POSTGRES_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
BETTER_AUTH_SECRET="$(openssl rand -base64 32)"
CRON_SECRET="$(openssl rand -hex 24)"
ENCRYPTION_KEY="$(openssl rand -base64 32)"
BASE_URL="https://${DOMAIN}"

cat > "$OUT" <<EOF
# Generated by deploy/init-env.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Edit optional fields (Resend, Google OAuth) after deploy.

# --- Server ---
DOMAIN=${DOMAIN}
POSTGRES_USER=meti
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=meti_booking

# --- Database (docker internal hostname) ---
DATABASE_URL=postgresql://meti:${POSTGRES_PASSWORD}@postgres:5432/meti_booking?schema=public

# --- Auth ---
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
BETTER_AUTH_URL=${BASE_URL}
NEXT_PUBLIC_BETTER_AUTH_URL=${BASE_URL}

# --- Self-hosted (enables local disk uploads instead of Vercel Blob) ---
SELF_HOSTED=1

# --- Studio ---
STUDIO_TIMEZONE=Europe/Athens
APP_URL=${BASE_URL}

# --- Security ---
CRON_SECRET=${CRON_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# --- Google OAuth (optional) ---
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# --- Email (Resend) — see deploy/RESEND.md ---
RESEND_API_KEY=
EMAIL_FROM="MeTi Pilates <bookings@${DOMAIN}>"
STUDIO_NOTIFICATION_EMAIL=tyrri_meropi@hotmail.com

# --- Mercado Pago (optional) ---
PAYMENTS_ENABLED=0
MERCADOPAGO_ACCESS_TOKEN=

# --- Demo seed (first deploy only — remove after) ---
# ALLOW_DEMO_SEED=1
# DEMO_PASSWORD=YourSecurePassword123!
EOF

chmod 600 "$OUT"
echo ""
echo "Wrote $OUT"
echo "  DOMAIN=${DOMAIN}"
echo "  Secrets generated (POSTGRES_PASSWORD, BETTER_AUTH_SECRET, CRON_SECRET, ENCRYPTION_KEY)"
echo ""
echo "Next:"
echo "  chmod +x deploy/*.sh"
echo "  ./deploy/deploy.sh"
