#!/usr/bin/env bash
# Write /etc/caddy/Caddyfile from DOMAIN in .env
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [[ ! -f .env ]]; then
  echo "Missing .env"
  exit 1
fi

# shellcheck disable=SC1091
set -a
source .env
set +a

if [[ -z "${DOMAIN:-}" ]]; then
  echo "DOMAIN not set in .env"
  exit 1
fi

WWW_BLOCK=""
if [[ "${DOMAIN}" != www.* ]]; then
  WWW_BLOCK="www.${DOMAIN} {
	redir https://${DOMAIN}{uri} permanent
}

"
fi

cat > /etc/caddy/Caddyfile <<EOF
# MeTi Booking — generated by deploy/setup-caddy-lite.sh
${WWW_BLOCK}${DOMAIN} {
	encode gzip
	reverse_proxy 127.0.0.1:3000
}
EOF

caddy validate --config /etc/caddy/Caddyfile
echo "Caddyfile written for ${DOMAIN}"
if [[ -n "${WWW_BLOCK}" ]]; then
  echo "www.${DOMAIN} redirects to https://${DOMAIN}"
fi
